name: Patch init_boot DSU


on:
  workflow_dispatch:


jobs:

  patch:

    runs-on: ubuntu-latest


    steps:


    - name: Checkout
      uses: actions/checkout@v4



    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          cpio \
          gzip \
          unzip \
          file \
          curl \
          wget



    - name: Get magiskboot
      run: |

        chmod +x tools/fetch-static-magiskboot.sh


        echo "Running fetch script..."


        bash tools/fetch-static-magiskboot.sh



        echo "Searching magiskboot..."


        find /tmp $HOME . -type f -name magiskboot 2>/dev/null || true



        MAGISKBOOT=$(find /tmp $HOME . -type f -name magiskboot 2>/dev/null | head -n 1)


        if [ -z "$MAGISKBOOT" ]; then

          echo "magiskboot not found"

          exit 1

        fi



        echo "Found: $MAGISKBOOT"


        cp "$MAGISKBOOT" ./magiskboot


        chmod 755 ./magiskboot


        ls -lh ./magiskboot


        file ./magiskboot



    - name: Check environment
      run: |

        echo "Current directory:"
        pwd


        echo "Files:"
        ls -lh


        echo "Test magiskboot:"


        ./magiskboot --help || true



    - name: Check input
      run: |

        test -f init_boot.img || exit 1

        test -f dsuinit || exit 1

        test -f dsu_permissive-android15-6.6.ko || exit 1


        ls -lh init_boot.img
        ls -lh dsuinit
        ls -lh dsu_permissive-android15-6.6.ko



    - name: Patch init_boot
      run: |

        chmod +x tools/patch-init-boot-android.sh
        chmod +x dsuinit


        ls -lh magiskboot


        bash tools/patch-init-boot-android.sh \
          --input ./init_boot.img \
          --output ./init_boot_dsu.img \
          --loader ./dsuinit \
          --module ./dsu_permissive-android15-6.6.ko \
          --selinux 1 \
          --avb 1 \
          --verity-table-spoof 1 \
          --magiskboot ./magiskboot



    - name: Upload
      uses: actions/upload-artifact@v4

      with:

        name: init_boot_dsu

        path: init_boot_dsu.img
