name: Patch init_boot

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y unzip cpio gzip

      - name: Download Magisk
        run: |
          wget -O Magisk.apk https://github.com/topjohnwu/Magisk/releases/latest/download/Magisk.apk
          unzip -o Magisk.apk -d magisk

      - name: Find magiskboot
        run: |
          find magisk -name "*magiskboot*"

      - name: Patch
        run: |
          chmod +x tools/*.sh

          chmod +x magisk/lib/x86_64/libmagiskboot.so

          cp magisk/lib/x86_64/libmagiskboot.so magiskboot

          chmod +x magiskboot

          bash tools/patch-init-boot-android.sh \
          --input init_boot.img \
          --output init_boot_dsu.img \
          --loader ./loader/dsuinit \
          --module ./out/dsu_permissive-android15-6.6.ko \
          --selinux 1 \
          --avb 1 \
          --verity-table-spoof 1 \
          --magiskboot ./magiskboot

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: init_boot_dsu
          path: init_boot_dsu.img
