name: Patch init_boot DSU


on:
  workflow_dispatch:


jobs:

  patch:

    runs-on: ubuntu-latest


    steps:


    - name: Checkout
      uses: actions/checkout@v4



    - name: Install tools
      run: |

        sudo apt update

        sudo apt install -y \
          wget \
          unzip \
          file \
          cpio \
          gzip



    - name: Download Magisk source
      run: |

        wget -O Magisk.apk \
        https://github.com/topjohnwu/Magisk/releases/download/v30.7/Magisk.apk


        mkdir magisk


        unzip -o Magisk.apk -d magisk



    - name: Find magiskboot
      run: |

        echo "Searching..."


        find magisk -type f | head -50



    - name: Prepare magiskboot
      run: |

        mkdir -p magiskboot_tmp


        unzip -o Magisk.apk \
        "lib/x86_64/libmagiskboot.so" \
        -d magiskboot_tmp || true


        find magiskboot_tmp



        cp $(find magiskboot_tmp -name libmagiskboot.so) magiskboot


        chmod +x magiskboot


        file magiskboot



    - name: Check
      run: |

        ./magiskboot --help || true



    - name: Patch init_boot
      run: |

        chmod +x tools/patch-init-boot-android.sh

        chmod +x dsuinit


        bash tools/patch-init-boot-android.sh \
        --input ./init_boot.img \
        --output ./init_boot_dsu.img \
        --loader ./dsuinit \
        --module ./dsu_permissive-android15-6.6.ko \
        --selinux 1 \
        --avb 1 \
        --verity-table-spoof 1 \
        --magiskboot ./magiskboot



    - name: Upload
      uses: actions/upload-artifact@v4

      with:

        name: init_boot_dsu

        path: init_boot_dsu.img
